from remark_lib import *

program = RemarkProgram()

program.everything_rule(prefix='#!/usr/bin/python\nfrom remark_lib import *\nprogram = RemarkProgram()\n')
program.everything_rule(suffix='program.run();')
program.untag_rule(target_tag='tag', transform=lambda tag: repr(tag) + ',')
program.untag_rule(target_tag='var', transform=lambda var: var.strip())
program.untag_rule(target_tag='target tag', prefix='target_tag=', transform=repr, suffix=',')
program.untag_rule(target_tag='preceeded by', prefix='tags_preceeding=[', suffix='],')
program.untag_rule(target_tag='followed by', prefix='tags_following=[', suffix='],')
program.untag_rule(target_tag="change target's tag", prefix='type="retag", new_tag=', transform=repr, suffix=',')
program.untag_rule(target_tag='unwrap target', prefix='type="untag",')
program.untag_rule(target_tag='prefix', prefix='prefix=', transform=repr, suffix=',')
program.untag_rule(target_tag='suffix', prefix='suffix=', transform=repr, suffix=',')
program.untag_rule(target_tag='transform', prefix='transform=', suffix=',')
program.untag_rule(target_tag='ammend', prefix='type="ammend",')
program.untag_rule(target_tag='textual', prefix='type="literal",')
program.untag_rule(target_tag='replace', prefix='find=', transform=repr, suffix=',')
program.untag_rule(target_tag='with', prefix='replace=', transform=repr, suffix=',')
program.untag_rule(target_tag='rule', prefix='program.rule(', suffix=');')
program.untag_rule(target_tag='target tag', tags_following=['var'], prefix='target_tag=', suffix=',')
program.untag_rule(target_tag='preceeded by', tags_following=['var'], prefix='tags_preceeding=', suffix=',')
program.untag_rule(target_tag='followed by', tags_following=['var'], prefix='tags_following=', suffix=',')
program.untag_rule(target_tag="change target's tag", tags_following=['var'], prefix='type="retag", new_tag=', suffix=',')
program.untag_rule(target_tag='prefix', tags_following=['var'], prefix='prefix=', suffix=',')
program.untag_rule(target_tag='suffix', tags_following=['var'], prefix='suffix=', suffix=',')
program.untag_rule(target_tag='replace', tags_following=['var'], prefix='find=', suffix=',')
program.untag_rule(target_tag='with', tags_following=['var'], prefix='replace=', suffix=',')
